### ISSUE TITLE
Web UI Camera input selection failing on Chrome/Mac

### ISSUE THREAD

**Issue by wilaw** [kixelated/moq-js#40]
Testing under Chrome 117.0.5938.88, mac 13.5.2, the quic.video/publish UI does not enumerate either of my video sources. Screen shot
![Screenshot 2023-09-25 at 2 58 37 PM](https://github.com/kixelated/moq-js/assets/2762250/a23e3500-d493-45ed-bce6-6ff35fcce6c0)

Here is https://webrtc.github.io/samples/src/content/devices/input-output/ for comparison
![Screenshot 2023-09-25 at 3 01 33 PM](https://github.com/kixelated/moq-js/assets/2762250/0fc3f218-33dc-493f-92fc-6f8bf4f4a706)

**Comment by zafergurel** [comment]
Did you allow camera and microphone access? Because if you skip it, enumerateDevices does not work.

I closed the permission request dialog and the page could not show my devices as follows:

<img width="1092" alt="image" src="https://github.com/kixelated/moq-js/assets/1393083/7f2e7968-fc9a-45f7-9084-67170dd4255e">

If that's the case, showing a warning to the user would be good.

**Comment by wilaw** [comment]
UI has changed when I went back to test. I do enable camera and mic access. Now it defaults to one of my camera, but there is no pull-down to select an alternate source. But the source it did select worked well :).

**Comment by kixelated** [comment]
Ya, I rewrote the publish form to be slicker. @zafergurel added the ability to select a device in #45 if you don't want the default.
